// qiankun-vue3-app3/src/App.vue
<template>
  <router-link to="/">home</router-link>
  <router-link to="/cat">cat</router-link>
  <router-link to="/dog">dog</router-link>
  <router-view></router-view>
  <h1>xxxxx</h1>
</template>

<script>
export default {
  name: 'App',
}
</script>

<style>
#app {
  margin: 10px, auto;
}
</style>

// qiankun-micro-app2/src/App.tsx
import React from 'react';
import './App.css';
import { Link, Route, Routes } from 'react-router-dom';
import Cat from './pages/Cat';
import Dog from './pages/Dog';

function App() {
  return (
    <div className="App">
      <Link to={"/"}>home</Link> |
      <Link to={"/cat"}>cat</Link> |
      <Link to={"/dog"}>dog</Link>
      <Routes>
        <Route path='/cat' element={<Cat />} />
        <Route path='/dog' element={<Dog/>} />
      </Routes>
    </div>
  );
}

export default App;
